// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3eT1YWHWGbzptFX_FEv29DxEmzlw1mZI',
    appId: '1:601256607386:android:ce5f96190468e50e5ae923',
    messagingSenderId: '601256607386',
    projectId: 'appointments-24f5d',
    storageBucket: 'appointments-24f5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOXZv4QWy8f440AvCrWI28MbPILGfy6yw',
    appId: '1:601256607386:ios:98fb36cc2d501de85ae923',
    messagingSenderId: '601256607386',
    projectId: 'appointments-24f5d',
    storageBucket: 'appointments-24f5d.appspot.com',
    iosClientId: '601256607386-vqk8p6qvs9hq579ukeiq4t9jbcn4sftd.apps.googleusercontent.com',
    iosBundleId: 'com.s.isa.developments.appointments',
  );
}
